# Generated by Django 5.2.1 on 2025-05-27 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_formadepagamento_produtovendido_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='FormaDePagamento',
            new_name='formaDePagamento',
        ),
        migrations.AddField(
            model_name='venda',
            name='horario',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
